# --
# File: python_utilities_consts.py
#
# --

PYTHONUTILITIES_SEARCH_STRING = 'search_string'
PYTHONUTILITIES_SOURCE_STRING = 'source_string'
PYTHONUTILITIES_SOURCE_STRING_START = 'source_string_start'
PYTHONUTILITIES_SOURCE_STRING_END = 'source_string_end'
PYTHONUTILITIES_SOURCE_STRING_STEP = 'source_string_step'
PYTHONUTILITIES_REGEX_ACTION = 'action'
PYTHONUTILITIES_REGEX_PATTERN = 'pattern'
PYTHONUTILITIES_REGEX_REPLACE = 'replace'
PYTHONUTILITIES_ITEM = 'item'
PYTHONUTILITIES_SPLIT_VALUE = 'split_value'
